### PR TITLE
Hardcoded version in readme to 1.0.9

### PR DESCRIPTION
**Pull request by berndruecker**

### CODE REVIEW

**Comment by berndruecker** [comment]
@celanthe Here we go

**Review by celanthe — COMMENTED** [review]
Thanks for this! I was wondering if we might want to implement the potential solution I had linked in #28 and try out https://github.com/Actions-R-Us/actions-tagger? 

If not, no worries, I can approve this and get that merged/cut a new release ASAP! Just let me know which approach you think is best. I am inclined to try out the actions-tagger due to the automated nature of it, personally. :)

**Comment by berndruecker** [comment]
I agree!

**Comment by celanthe** [comment]
Hi @berndruecker! As we've gotten the action to work with @v1, I was wondering if we should close this? Thanks so much!

**Comment by berndruecker** [comment]
Yes - make sense

Sent from a mobile device
________________________________

**Comment by celanthe** [comment]
Closing this due to resolution implemented in #28

**Pull request closed without merging**
