### PR TITLE
Fix: Update uses tag

### PR DESCRIPTION
**Pull request by celanthe**
Updated `uses` tags to reference most recent release of v1.0.9

Fixes: #25

### CODE REVIEW

**Comment by berndruecker** [comment]
As discussed in https://github.com/camunda-community-hub/community-action-maven-release/issues/25 this can be closed

**Comment by celanthe** [comment]
Hi @berndruecker! :) I just wanted to circle back on this as I'd love to get it merged to hopefully resolve #25. If you would be so kind as to review it whenever you get a moment, that would be amazing. Thank you so much!

**Comment by berndruecker** [comment]
Hi @celanthe - I am actually not sure if that fixes the problem. I am not deep enough in how Github actions work - and still pulled that the latest version is not just picked up as written in the docs (could the "v" in "v1.0.9" be a problem?). 
So if you think that helps I would say go ahead and we see what happens :-)

**Comment by celanthe** [comment]
@berndruecker Fantastic! I did a bit more research into this, and for now I'm going to merge this and see if it resolves the issue in #25. If not, I'll open another issue and add my findings there so we can continue debugging this.

**Comment by berndruecker** [comment]
So, would now be a good time to test if anything changed @celanthe?

**Comment by berndruecker** [comment]
Looks like it is still using an too old v1 if I don't specify to use v1.0.9, see https://github.com/camunda-community-hub/spring-zeebe/commit/bfb4677ac8c6bd0b470524b5a08c0109e47a619e leads to https://github.com/camunda-community-hub/spring-zeebe/runs/4372925957?check_suite_focus=true

**Comment by celanthe** [comment]
Thank you kindly for testing that out @berndruecker I'm so sorry to hear that it's not working as intended and am doing my best to look into possible solutions. I've got a new issue open for this over at https://github.com/camunda-community-hub/community-action-maven-release/issues/28 that I hope will help us get to the bottom of this! :)

**Pull request merged**
